# This is a basic workflow to help you get started with Actions

name: Trigger Benchmark

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  BenchmarkTrigger:
    runs-on: ubuntu-latest
    steps:                      
    - name: 'Checkout recursive' 
      uses: actions/checkout@v2
      with:        
        submodules: recursive                
   
    - name: 'CMake Build'
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        configure-options: -DFASTNOISE2_NOISETOOL=OFF -DFASTNOISE2_TESTS=ON -DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_FLAGS=-m64
    
    - name: 'Upload artifact'
      uses: actions/upload-artifact@v2
      with:
        name: Linux64-TestsBin
        path: ${{ github.workspace }}/build/

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: Auburn/FastNoise2Benchmarking
        event-type: benchmark
