name: Release

on:
  push:
    branches: [master]
  create:  
   tags:
      - v*

jobs:   
  check-release:
    runs-on: ubuntu-latest
    steps:      
    - name: 'Checkout' 
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0        
      
    - name: 'Check new CMake version'
      id: cmake-ver
      run: |
        for commit in $(git rev-list master)
        do
          git checkout --quiet $commit
          cmake_ver=v$(grep -oEi 'project\s*\(\s*FastNoise2.*VERSION\s+([[:digit:]\.]+)\s*\)' CMakeLists.txt | grep -oEi '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+')
          
          if echo "$cmake_ver" | grep '^v0\.'; then 
            cmake_ver="${cmake_ver}-alpha"
          fi
          
          if git show-ref --tags $cmake_ver --quiet; then
            echo "$cmake_ver exists"
            if echo $cmake_ver | grep -oEi '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'; then
              echo "::set-output name=new-tag::$prev_cmake_ver"
              echo "::set-output name=tag-commit::$prev_commit"
            fi
            break
          else
            echo "$cmake_ver not found"
            prev_commit=$commit
            prev_cmake_ver=$cmake_ver
          fi
        done
    
    - name: 'Create tag'
      if: ${{ steps.cmake-ver.outputs.new-tag != '' }}
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.cmake-ver.outputs.new-tag }}",
            sha: "${{ steps.cmake-ver.outputs.tag-commit }}"
          })
    
    - uses: fregante/release-with-changelog@main
      if: ${{ steps.cmake-ver.outputs.new-tag != '' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude: '^Update\s\S+\.(md|yml)$'
        tag: ${{ steps.cmake-ver.outputs.new-tag }}
        draft: true
        template: |
          ### Changelog

          {commits}

          {range}
