name: Release

on:
  push:
    branches: [master]
    tags:
      - v*

jobs:   
  check-release:
    runs-on: ubuntu-latest
    steps:      
    - name: 'Checkout' 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0        
      
    - name: 'Check new CMake version'
      id: cmake-ver
      run: |
        for commit in $(git rev-list master)
        do
          git checkout --quiet $commit
          cmake_ver=v$(grep -oEi 'project\s*\(\s*FastNoise2.*VERSION\s+([[:digit:]\.]+)\s*\)' CMakeLists.txt | grep -oEi '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+')
          
          if echo "$cmake_ver" | grep '^v0\.'; then 
            cmake_ver="${cmake_ver}-alpha"
          fi
          
          if git show-ref --tags $cmake_ver --quiet; then
            echo "$cmake_ver exists"
            git pull origin master
            if git tag "$prev_cmake_ver" $prev_commit; then
              git push origin $prev_cmake_ver
              echo "::set-output name=new-tag::$prev_cmake_ver"
            fi
            break
          else
            echo "$cmake_ver not found"
            prev_commit=$commit
            prev_cmake_ver=$cmake_ver
          fi
        done
        
    - uses: fregante/release-with-changelog@main
      if: ${{ steps.cmake-ver.outputs.new-tag != '' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude: '^Update\s\S+\.(md|yml)$'
        tag: ${{ steps.cmake-ver.outputs.new-tag }}
        draft: true
        template: |
          ### Changelog

          {commits}

          {range}
